{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Cross validation"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Imports"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 739, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 988, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "  File \"src\\pymssql\\_pymssql.pyx\", line 316, in pymssql._pymssql.Connection.rollback\n",
      "  File \"src\\pymssql\\_pymssql.pyx\", line 300, in pymssql._pymssql.Connection.rollback\n",
      "  File \"src\\pymssql\\_mssql.pyx\", line 1056, in pymssql._mssql.MSSQLConnection.execute_non_query\n",
      "  File \"src\\pymssql\\_mssql.pyx\", line 1077, in pymssql._mssql.MSSQLConnection.execute_non_query\n",
      "  File \"src\\pymssql\\_mssql.pyx\", line 1251, in pymssql._mssql.MSSQLConnection.format_and_run_query\n",
      "  File \"src\\pymssql\\_mssql.pyx\", line 1789, in pymssql._mssql.check_cancel_and_raise\n",
      "  File \"src\\pymssql\\_mssql.pyx\", line 1835, in pymssql._mssql.raise_MSSQLDatabaseException\n",
      "pymssql._mssql.MSSQLDatabaseException: (20047, b'DB-Lib error message 20047, severity 9:\\nDBPROCESS is dead or not enabled\\n')\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from sqlalchemy import create_engine\n",
    "\n",
    "server = \"mssql-82792-0.cloudclusters.net:16272\"\n",
    "username = \"user\"\n",
    "password = \"RiceOwls1912\" \n",
    "database = \"ghz\"\n",
    "string = \"mssql+pymssql://\" + username + \":\" + password + \"@\" + server + \"/\" + database\n",
    "\n",
    "conn = create_engine(string).connect()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## EXAMPLE: TRAIN FROM 2021-12, PREDICT FOR 2022-01"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_sql(\n",
    "    \"\"\"\n",
    "    select ticker, date, agr, bm, idiovol, mom12m, roeq, ret\n",
    "    from data\n",
    "    where date in ('2021-12', '2022-01')\n",
    "    \"\"\", \n",
    "    conn\n",
    ")\n",
    "features = [\"agr\", \"bm\", \"idiovol\", \"mom12m\", \"roeq\"]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## TRANSFORM EACH CROSS-SECTION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.preprocessing import QuantileTransformer\n",
    "qt = QuantileTransformer(output_distribution=\"normal\")\n",
    "\n",
    "def qtxs(d):\n",
    "    x = qt.fit_transform(d)\n",
    "    return pd.DataFrame(x, columns=d.columns, index=d.index)\n",
    "\n",
    "df[features + [\"ret\"]] = df.groupby(\n",
    "  \"date\", \n",
    "  group_keys=False\n",
    ")[features + [\"ret\"]].apply(qtxs)"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## FITTING A RANDOM FOREST"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "from scipy.stats import spearmanr\n",
    "from sklearn.metrics import make_scorer\n",
    "\n",
    "scorer = make_scorer(\n",
    "    lambda a, b: spearmanr(a, b).statistic, \n",
    "    greater_is_better=True\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Risto Trajanov\\AppData\\Local\\Temp\\ipykernel_123248\\1467376756.py\", line 5, in <lambda>\n",
      "    lambda a, b: spearmanr(a, b).statistic,\n",
      "AttributeError: 'SpearmanrResult' object has no attribute 'statistic'\n",
      "\n",
      "  UserWarning,\n",
      "c:\\Users\\Risto Trajanov\\anaconda3\\envs\\myenv\\lib\\site-packages\\sklearn\\model_selection\\_search.py:972: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan]\n",
      "  category=UserWarning,\n"
     ]
    }
   ],
   "source": [
    "from sklearn.ensemble import RandomForestRegressor\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "\n",
    "df = df.dropna()\n",
    "\n",
    "X = df[df.date=='2021-12'][features]\n",
    "y = df[df.date=='2021-12'][\"ret\"]\n",
    "\n",
    "model = RandomForestRegressor()\n",
    "\n",
    "cv = GridSearchCV(\n",
    "  model,\n",
    "  param_grid={\n",
    "    \"max_depth\": range(1, 11)\n",
    "  },\n",
    "  scoring=scorer\n",
    ")\n",
    "_ = cv.fit(X, y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]\n"
     ]
    }
   ],
   "source": [
    "scores = [x for x in cv.cv_results_['mean_test_score']]\n",
    "print(scores)"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## GRIDSEARCHCV FOR MULTI-LAYER PERCEPTRON"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "param_grid={\n",
    "    \"hidden_layer_sizes\": [\n",
    "        [16, 8, 4, 2], \n",
    "        [16, 8, 4],\n",
    "        [8, 4, 2], \n",
    "        [16, 8],\n",
    "        [16, 4],\n",
    "        [8, 4],\n",
    "        [4, 4],\n",
    "        [4, 2]\n",
    "    ]\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "cv = GridSearchCV(\n",
    "  MLPRegressor(max_iter=500)\n",
    "  param_grid=param_grid,\n",
    "  scoring=scorer\n",
    ")\n",
    "_ = cv.fit(X, y)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "myenv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.13"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "09ac0f642c4809c63ace70dc888cbd5b35159287af3895fb76989324c78b2f31"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
